#!/bin/bash
### BEGIN INIT INFO
# Provides:          scriptname
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start carnation resque worker 
# Description:       start carnation resque worker
### END INIT INFO
#
# carnation API server startup script for unicorn
# set rbenv environment valiables
#
export PATH=/usr/local/bin:/usr/bin:/bin
set -e

APP_ROOT="/home/carnation/magoch_server"
PIDFILE="$APP_ROOT/resque/worker.pid"
ENVFILE="$APP_ROOT/production.env"
. $ENVFILE
echo CARNATION_MYSQL_HOST=$CARNATION_MYSQL_HOST
echo CARNATION_REDIS_HOST=$CARNATION_REDIS_HOST
echo CARNATION_S3_BUCKET_NAME=$CARNATION_S3_BUCKET_NAME
echo RACK_ENV=$RACK_ENV
cd $APP_ROOT || exit 1

signal(){
  test -s "$PIDFILE" && kill -$1 `cat $PIDFILE`
}

case $1 in
start)
  signal 0 && echo >&2 "carnation resque worker is already running" && exit 0
  cd $APP_ROOT 
  rake resque:start
  ;;
stop)
  if [ -e $PIDFILE ] 
  then
    cd $APP_ROOT 
    rake resque:stop
  else
    echo "resque worker is not running"
  fi
  ;;
restart)
  cd $APP_ROOT 
  rake server:stop
  rake server:start
  ;;
*)
  echo >&2 "Usage: $0 <start|stop|restart>"
  exit 1
  ;;
esac
